(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},n;if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var ba={da:!0},q={};try{q.__proto__=ba;p=q.da;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var r=n,t=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]},ca=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},u=ca(this),goog=goog||{},da=this||self,ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},w=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var x=function(a,b,c,d){a="translate3d("+a+"px, "+b+"px, "+c+"px)";d&&(a="rotate3d(0, 1, 0, "+d+"deg) "+a);return a},y=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a};var z=["-ms-","-moz-","-webkit-",""],B=function(a,b,c,d){d=void 0===d?!1:d;for(var e,m,f=0;f<z.length;f++)e=z[f]+b,m=(d?z[f]:"")+c,a.style.setProperty(e,m)};var C=function(a,b){B(a,"transition","transform "+b+"ms",!0)};var D=function(a,b){return window.setTimeout(a,b)};var E=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},fa=function(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;D(function(){var d=E("autoplayended",a,b);c&&c(d)},0)},ha=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},ia=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=D(function(){c=null;b&&(a(),b=!1)},250))}};var F=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},G=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ja=function(a){if(G(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&G(a))return a;return null},H=function(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,
a)):c.removeAttribute(d)},ka=function(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};var la=function(a){a=a.trim();return window.Enabler?window.Enabler.getUrl(a):a};var I=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,I);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};w(I,Error);I.prototype.name="CustomError";var J=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");I.call(this,c+a[d])};w(J,I);J.prototype.name="AssertionError";var ma=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new J(""+d,e||[]);}return a},na=function(a,b){throw new J("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var K=function(){this.J=""};K.prototype.m=!0;K.prototype.l=function(){return this.J.toString()};K.prototype.toString=function(){return"SafeScript{"+this.J+"}"};K.prototype.h=function(a){this.J=a};(new K).h("");var N=function(a,b){this.M=a===L&&b||"";this.ca=M};N.prototype.m=!0;N.prototype.l=function(){return this.M.toString()};N.prototype.toString=function(){return"SafeUrl{"+this.M+"}"};var oa=function(a){if(a instanceof N&&a.constructor===N&&a.ca===M)return a.M;na("expected object of type SafeUrl, got '"+a+"' of type "+ea(a));return"type_error:SafeUrl"},pa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,M={},L={};var O=function(){this.L=""};O.prototype.m=!0;O.prototype.l=function(){return this.L};O.prototype.toString=function(){return"SafeStyle{"+this.L+"}"};O.prototype.h=function(a){this.L=a};(new O).h("");var P=function(){this.K=""};P.prototype.m=!0;P.prototype.l=function(){return this.K};P.prototype.toString=function(){return"SafeStyleSheet{"+this.K+"}"};P.prototype.h=function(a){this.K=a};(new P).h("");var Q=function(){this.I=""};Q.prototype.m=!0;Q.prototype.l=function(){return this.I.toString()};Q.prototype.toString=function(){return"SafeHtml{"+this.I+"}"};Q.prototype.h=function(a){this.I=a};(new Q).h("<!DOCTYPE html>");(new Q).h("");(new Q).h("<br>");var qa=function(a){var b=document.createElement("gwd-image");b.setAttribute("source",a);return b},R=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)/^[\s\xa0]*$/.test(a[c])||b.push(qa(la(a[c])))}return b},S=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}},T=function(a,b){return"left"==a||"backwards"==a?-b:b},ra=function(a,b){return(a%b+b)%b};var sa=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},U=function(a,b){this.i=a;this.o=null;this.pa=b;this.F=!1};
U.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.i.frameCount&&null==this.o){if(c){var e=Math.floor(a/c);a=c}else e=this.i.frameCount,a/=e;var m=[],f=sa(this.i);c=f;for(var h=0;h<e;h++){if(0<h||!this.pa)c=ra(c+T(b,1),this.i.frameCount);m.push(c)}b=function(){if(m.length){var k=m.shift();d.F=!0;d.i.goToFrame(k+1);d.F=!1;E("frameautoplayed",d.i,{id:k+1})}else d.stop(!0),d.i.goToFrame(f+1)};this.o=window.setInterval(b,a);setTimeout(b)}};
U.prototype.stop=function(a){a=void 0===a?!1:a;!this.F&&this.o&&(window.clearInterval(this.o),fa(this.i,{completed:a}),this.o=null)};var ta=["pause-front-media","resume-next-media"],V=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.a=null;a.b=0;a.w=1;a.u=new U(a,!0);a.W=!1;a.Y=!1;return a};t(V,HTMLElement);g=V.prototype;g.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.W="true"==c;break;case "resume-next-media":this.Y="true"==c}};g.gwdIsLoaded=function(){return!0};g.gwdLoad=function(){};g.goToFrame=function(a,b){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.R(a,b))};
g.R=function(a){this.a=a-1};var ua=function(a,b,c,d){if(null!=a.a){var e=a.w;e=ra(a.a+T(b,void 0===e?1:e),a.w*Math.ceil(a.b/a.w));!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c)}};g=V.prototype;g.goBackwards=function(a,b){ua(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};g.goForwards=function(a,b){ua(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};g.rotateOnce=function(a,b){this.u.play(void 0===a?0:a,b)};g.stopRotation=function(){this.u.stop()};
g.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};var va=function(a,b){if(null!=a.a&&a.a!=b){if(a.W)for(var c=Array.prototype.slice.call(a.frames[a.a].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),d=0;d<c.length;d++){var e=c[d];e.pause&&e.pause()}if(a.Y)for(a=Array.prototype.slice.call(a.frames[b].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),b=0;b<a.length;b++)c=a[b],c.play&&c.play()}};
V.prototype.ea=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?E(d,this,{id:this.currentIndex}):E(d,this)}};u.Object.defineProperties(V.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.b?this.a+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.w}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.b}}});
u.Object.defineProperties(V,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ta}}});var wa="autoplay exit-urls transition-duration frame-width frame-height neighbor-rotation-y neighbor-translation-x neighbor-translation-y neighbor-translation-z start-frame show-reflection has-navigation navigation-highlight navigation-thumbnails images scaling pause-front-media resume-next-media".split(" "),W=function(){var a=V.call(this)||this;a.G=!1;a.g=null;a.S=-1;a.N=0;a.j=null;a.ba=a.na.bind(a);a.aa=a.oa.bind(a);a.$=a.ma.bind(a);a.Z=a.la.bind(a);a.D=E.bind(null,"firstinteraction",a);a.V=a.ja.bind(a);
a.X=ia(a.ka.bind(a));a.O=!1;a.H=[];a.s=a.ea.bind(a,a.H);a.C=[];a.P=0;a.A=!1;a.c=null;a.v=0;a.u=new U(a,!1);a.f=null;a.T=!1;a.B=!1;return a};t(W,V);g=W.prototype;
g.connectedCallback=function(){if(!this.B){if(this.A=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.j=a;this.B=!0}a=this.j;this.v=this.v||this.clientWidth/2;a.addEventListener("trackstart",this.ba,!1);a.addEventListener("track",this.aa,!1);a.addEventListener("trackend",this.$,!1);a.addEventListener("tap",this.Z,!1);this.addEventListener("transitionend",this.s,!1);this.addEventListener("webkitTransitionEnd",
this.s,!1);this.gwdIsLoaded()||((a=ja(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.T&&X(this);window.addEventListener("resize",this.X,!1)};
g.disconnectedCallback=function(){window.removeEventListener("resize",this.X,!1);var a=this.j;a.removeEventListener("trackstart",this.ba,!1);a.removeEventListener("track",this.aa,!1);a.removeEventListener("trackend",this.$,!1);a.removeEventListener("tap",this.Z,!1);this.removeEventListener("transitionend",this.s);this.removeEventListener("webkitTransitionEnd",this.s)};
g.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":this.A=!0;this.b=0;this.a=null;this.frames=R(c||"");X(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":this.B&&xa(this);break;case "scaling":S(this.frames,c);break;case "pause-front-media":case "resume-next-media":V.prototype.attributeChangedCallback.call(this,a,b,c,d);break;default:ya(this)}};
g.R=function(a,b){b="none"!=b;var c=this.c.transitionDuration;va(this,a-1);Y(this,b?c:0);Z(this,a-1)};g.rotateOnce=function(a,b){this.u.play((void 0===a?0:a)||this.c.transitionDuration*this.b,b)};g.gwdIsLoaded=function(){return this.G};g.gwdLoad=function(){if(!this.G&&!this.g){if(this.A)var a=R(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;X(this)}};
var X=function(a){if(a.B){for(;a.firstChild;)a.removeChild(a.firstChild);a.f=null;a.g&&a.g.removeEventListener("pageload",a.V,!1);for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];B(e,"user-select","none");e.classList.add("frame");c.appendChild(e)}ha(c,c.gwdLoad.bind(c));a.g=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.V,!1);S(a.frames,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.j)}else a.T=
!0};W.prototype.ja=function(a){this.g===a.target&&(this.G=!0,this.b=this.frames.length,this.C=[],this.P=this.b,za(this),this.b&&this.c.autoplay&&D(this.rotateOnce.bind(this),0),xa(this),E("allframesloaded",this),E("ready",this))};var za=function(a){Aa(a);if(a.b){var b=a.c.qa-1;if(0>b||b>=a.b)b=0;Y(a,0);Z(a,b)}};W.prototype.ka=function(){this.v=this.clientWidth/2;za(this)};
var Aa=function(a){ya(a);for(var b=0,c,d=0;d<a.frames.length;d++)c=a.frames[d],c.style.left=b+"px",c.style.width=a.c.frameWidth+"px",c.style.height=a.c.frameHeight+"px",b+=a.c.frameWidth},ya=function(a){var b=a.frames;var c=y(a,"frame-width",Math.floor(.8*a.clientWidth));var d=a.hasAttribute("show-reflection"),e=y(a,"frame-height",d?Math.floor(4*a.clientHeight/7):Math.floor(6*a.clientHeight/7)),m=y(a,"neighbor-translation-x",Math.floor(c/8));if(a.hasAttribute("neighbor-translation-x")){a:{var f=c,
h=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var k=a.getAttribute("clamp-frame-size-to-image");"true"==k?h=!0:"false"==k&&(h=!1)}if(h)if(k=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",(h="contain"==k)||"none"==k)if(0==f||0==e)b=f;else{k=-1;c=b.length;for(var A=0;A<c;A++){var l=b[A];if("img"!=l.tagName.toLowerCase()&&"gwd-image"!=l.tagName.toLowerCase()){b=f;break a}var v=l.assetWidth?l.assetWidth:l.naturalWidth;l=l.assetHeight?l.assetHeight:l.naturalHeight;0<v&&0<l&&(k=Math.max(k,
h?v/l<f/e?v/l*e:f:v))}b=-1!=k?Math.min(f,k):f}else b=f;else b=f}c=b}b=y(a,"neighbor-translation-y",-Math.floor(e/10));f=y(a,"neighbor-translation-z",-e);h=y(a,"neighbor-rotation-y",38);k=y(a,"start-frame",2);v=e;a.f&&(v-=36);e=ka(a);A=a.hasAttribute("autoplay");l=parseInt(a.getAttribute("transition-duration"),10);isNaN(l)&&(l=600);a.c={autoplay:A,fa:e,frameWidth:c,frameHeight:v,ga:h,ha:m,U:b,ia:f,transitionDuration:l,ra:d,qa:k}};
W.prototype.na=function(){null!=this.a&&(this.stopRotation(),this.N=this.a,Y(this,0))};W.prototype.oa=function(a){if(this.b){this.D&&(this.D(),this.D=null);a=-a.dx/this.c.frameWidth;var b=Math.round(a);Ba(this,this.N+b,a-b)}};W.prototype.ma=function(){if(null!=this.a){Y(this,this.c.transitionDuration);var a=this.a;Z(this,a);this.N!=a&&(0==a?E("reachleftend",this):a==this.b-1&&E("reachrightend",this))}};
W.prototype.la=function(a){if(this.b){var b=null;var c=this.j;var d=this.g,e=a.clientX,m=a.clientY,f=c.style["pointer-events"];c.style["pointer-events"]="none";e=d.ownerDocument.elementFromPoint(e,m);c.style["pointer-events"]=f;if(c=e&&F(d,e)?e:null){d=a.clientX;a=a.clientY;f=!1;"gwd-taparea"===c.tagName.toLowerCase()&&(f=c.ownerDocument.createEvent("Event"),f.initEvent("action",!0,!0),f.clientX=d,f.clientY=a,f=!c.dispatchEvent(f));if(f)return;for(a=0;a<this.b;a++)if(F(this.frames[a],c)){b=a;break}null!=
b&&(a=this.c.fa[b])&&!E("frameexit",this,{url:a}).detail.handled&&(a instanceof N||a instanceof N||(a="object"==typeof a&&a.m?a.l():String(a),ma(pa.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new N(L,a)),da.open(oa(a),"",void 0,void 0))}null==b&&(b=null!=this.a?this.a:0);E("frametap",this,{element:this.frames[b],id:b+1})}};
var Y=function(a,b){a.O=0<b;a.g&&C(a.g,b);for(var c=0;c<a.b;c++)C(a.frames[c],b)},Z=function(a,b){a.frames[b]&&(a.a=b,Ba(a,b,0,a.b),a.H.push("frameshown"),a.C[b]||(a.C[b]=!0,--a.P||a.H.push("allframesviewed")));a.O||a.s()},Ba=function(a,b,c,d){d=void 0===d?1:d;for(var e=a.c,m,f,h=-d;h<=d;h++)if((m=a.frames[h+b])&&0<=c*h){0>h?f=1-Math.abs(c):0<h?f=Math.abs(c)-1:(va(a,b),a.a=b,f=c);var k=Math.abs(f);m.style.setProperty("transform",x(e.ha*f,e.U*k,e.ia*k,e.ga*f))}a.S!=a.a&&null!=a.a&&(a.S=a.a,E("frameactivated",
a,{id:a.currentIndex}));a.g.style.setProperty("transform",x(a.v-(b+c+.5)*e.frameWidth,-e.U,0,void 0))},xa=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.f;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.f=document.createElement("gwd-gallerynavigation"),a.f.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.f)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.f),a.f=null);a.f&&(H(a,"navigation-highlight",a.f,"highlight"),H(a,"navigation-thumbnails",a.f,
"use-thumbnails"));Aa(a)};u.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return wa}}});customElements.define("gwd-carouselgallery",W);}).call(this);
