(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var m={v:!0},p={};try{p.__proto__=m;l=p.v;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var q=k,r=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},t=r(this),goog=goog||{};var u=function(){this.o=""};u.prototype.toString=function(){return"SafeScript{"+this.o+"}"};u.prototype.c=function(a){this.o=a};(new u).c("");var v=function(){this.u=""};v.prototype.toString=function(){return"SafeStyle{"+this.u+"}"};v.prototype.c=function(a){this.u=a};(new v).c("");var x=function(){this.s=""};x.prototype.toString=function(){return"SafeStyleSheet{"+this.s+"}"};x.prototype.c=function(a){this.s=a};(new x).c("");var y=function(){this.m=""};y.prototype.toString=function(){return"SafeHtml{"+this.m+"}"};y.prototype.c=function(a){this.m=a};(new y).c("<!DOCTYPE html>");(new y).c("");(new y).c("<br>");var z="currentIndex frameCount frameSnapInterval getFrame goToFrame goForwards goBackwards rotateOnce".split(" ");var A={B:"for",C:"highlight",D:"use-thumbnails"},B=[],C=0,D;for(D in A)B[C++]=A[D];var E=function(){var a=HTMLElement.call(this)||this;a.a=null;a.j=a.A.bind(a);a.i=a.w.bind(a);a.h=!1;a.b=null;a.f=[];a.g=!1;return a},F=HTMLElement;E.prototype=d(F.prototype);E.prototype.constructor=E;if(q)q(E,F);else for(var G in F)if("prototype"!=G)if(Object.defineProperties){var H=Object.getOwnPropertyDescriptor(F,G);H&&Object.defineProperty(E,G,H)}else E[G]=F[G];
E.prototype.connectedCallback=function(){if(!this.g){for(;this.firstChild;)this.removeChild(this.firstChild);this.b=this.ownerDocument.createElement("div");this.b.classList.add("button-container");this.appendChild(this.b);this.g=!0}this.b.addEventListener("click",this.l.bind(this),!0);I(this)};E.prototype.disconnectedCallback=function(){this.b.removeEventListener("click",this.l.bind(this));J(this)};E.prototype.attributeChangedCallback=function(a){if(this.g)switch(a){case "for":I(this);break;default:K(this)}};
var I=function(a){J(a);var b=a.getAttribute("for"),c=null,f=!1;if(b){c=document.getElementById(b);for(var g=!1,e=a.parentElement;!c&&e&&!g;e=e.parentElement)if((g="body"==e.tagName.toLowerCase())||e.hasAttribute("data-gwd-group"))c=e.querySelector('[data-gwd-grp-id="'+b+'"]');if(c)a:if(c){for(b=0;b<z.length;b++)if(!(z[b]in c)){f=!1;break a}f=!0}else f=!1}f&&(a.a=c,c.addEventListener("frameactivated",a.i),c.gwdIsLoaded()?K(a):c.addEventListener("ready",a.j))},J=function(a){a.a&&(a.a.removeEventListener("ready",
a.j),a.a.removeEventListener("frameactivated",a.i))};E.prototype.A=function(a){a.target==this.a&&K(this)};E.prototype.w=function(a){a.target==this.a&&L(this,a.detail.id)};E.prototype.l=function(a){for(a=a.target;a&&a!=this;a=a.parentElement)if(a.gwdTargetFrameNum){this.a.goToFrame(a.gwdTargetFrameNum);break}};
var K=function(a){var b=a.getAttribute("highlight");a.style.color=b||"";a.h=a.hasAttribute("use-thumbnails");for(a.f=[];a.b.firstChild;)a.b.removeChild(a.b.firstChild);if(a.a){b=a.a.frameSnapInterval||1;for(var c=a.h?b:1,f=0;f<a.a.frameCount;f+=b){var g=document.createElement("span");g.classList.add("button");for(var e=0;e<c;e++){var h=a.a.getFrame(f+e+1);if(!h)break;var w=void 0,n=document.createElement("span");a.h?(n.classList.add("frame-thumbnail"),(h="gwd-image"==h.tagName.toLowerCase()||"img"==
h.tagName.toLowerCase()?h:h.querySelector("gwd-image"))&&(w=h.getAttribute("source")||h.getAttribute("src")),n.style.backgroundImage=w?"url("+JSON.stringify(w)+")":"url(data:image/gif;base64,R0lGODlhAQABAPAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==)"):n.classList.add("frame-dot");g.appendChild(n)}g.gwdTargetFrameNum=f+1;a.f.push(g);a.b.appendChild(g)}L(a)}},L=function(a,b){b=void 0!=b?b-1:a.a.currentIndex-1;a.a.frameSnapInterval&&(b=Math.floor(b/a.a.frameSnapInterval));for(var c=0;c<a.f.length;c++)a.f[c].classList.remove("active");
(a=a.f[b])&&a.classList.add("active")};t.Object.defineProperties(E,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return B}}});customElements.define("gwd-gallerynavigation",E);}).call(this);
